# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_service_pb2 as order__service__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/tradeflow.order.OrderService/SubmitOrder',
                request_serializer=order__service__pb2.SubmitOrderRequest.SerializeToString,
                response_deserializer=order__service__pb2.SubmitOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/tradeflow.order.OrderService/GetOrderBook',
                request_serializer=order__service__pb2.GetOrderBookRequest.SerializeToString,
                response_deserializer=order__service__pb2.GetOrderBookResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/tradeflow.order.OrderService/CancelOrder',
                request_serializer=order__service__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=order__service__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/tradeflow.order.OrderService/ModifyOrder',
                request_serializer=order__service__pb2.ModifyOrderRequest.SerializeToString,
                response_deserializer=order__service__pb2.ModifyOrderResponse.FromString,
                _registered_method=True)
        self.SubscribeTrades = channel.unary_stream(
                '/tradeflow.order.OrderService/SubscribeTrades',
                request_serializer=order__service__pb2.SubscribeTradesRequest.SerializeToString,
                response_deserializer=order__service__pb2.TradeUpdate.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=order__service__pb2.SubmitOrderRequest.FromString,
                    response_serializer=order__service__pb2.SubmitOrderResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=order__service__pb2.GetOrderBookRequest.FromString,
                    response_serializer=order__service__pb2.GetOrderBookResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=order__service__pb2.CancelOrderRequest.FromString,
                    response_serializer=order__service__pb2.CancelOrderResponse.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=order__service__pb2.ModifyOrderRequest.FromString,
                    response_serializer=order__service__pb2.ModifyOrderResponse.SerializeToString,
            ),
            'SubscribeTrades': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTrades,
                    request_deserializer=order__service__pb2.SubscribeTradesRequest.FromString,
                    response_serializer=order__service__pb2.TradeUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradeflow.order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradeflow.order.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeflow.order.OrderService/SubmitOrder',
            order__service__pb2.SubmitOrderRequest.SerializeToString,
            order__service__pb2.SubmitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeflow.order.OrderService/GetOrderBook',
            order__service__pb2.GetOrderBookRequest.SerializeToString,
            order__service__pb2.GetOrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeflow.order.OrderService/CancelOrder',
            order__service__pb2.CancelOrderRequest.SerializeToString,
            order__service__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeflow.order.OrderService/ModifyOrder',
            order__service__pb2.ModifyOrderRequest.SerializeToString,
            order__service__pb2.ModifyOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tradeflow.order.OrderService/SubscribeTrades',
            order__service__pb2.SubscribeTradesRequest.SerializeToString,
            order__service__pb2.TradeUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
