// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

package com.tradeflow.order;

public interface GetOrderBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflow.order.GetOrderBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  java.util.List<com.tradeflow.order.OrderBookEntry> 
      getBidsList();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  com.tradeflow.order.OrderBookEntry getBids(int index);
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  int getBidsCount();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
      getBidsOrBuilderList();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  com.tradeflow.order.OrderBookEntryOrBuilder getBidsOrBuilder(
      int index);

  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  java.util.List<com.tradeflow.order.OrderBookEntry> 
      getAsksList();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  com.tradeflow.order.OrderBookEntry getAsks(int index);
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  int getAsksCount();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
      getAsksOrBuilderList();
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  com.tradeflow.order.OrderBookEntryOrBuilder getAsksOrBuilder(
      int index);
}
