// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

package com.tradeflow.order;

/**
 * Protobuf type {@code tradeflow.order.GetOrderBookResponse}
 */
public final class GetOrderBookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflow.order.GetOrderBookResponse)
    GetOrderBookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetOrderBookResponse.newBuilder() to construct.
  private GetOrderBookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetOrderBookResponse() {
    bids_ = java.util.Collections.emptyList();
    asks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetOrderBookResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetOrderBookResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              bids_ = new java.util.ArrayList<com.tradeflow.order.OrderBookEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            bids_.add(
                input.readMessage(com.tradeflow.order.OrderBookEntry.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              asks_ = new java.util.ArrayList<com.tradeflow.order.OrderBookEntry>();
              mutable_bitField0_ |= 0x00000002;
            }
            asks_.add(
                input.readMessage(com.tradeflow.order.OrderBookEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        bids_ = java.util.Collections.unmodifiableList(bids_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        asks_ = java.util.Collections.unmodifiableList(asks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflow.order.OrderServiceOuterClass.internal_static_tradeflow_order_GetOrderBookResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflow.order.OrderServiceOuterClass.internal_static_tradeflow_order_GetOrderBookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflow.order.GetOrderBookResponse.class, com.tradeflow.order.GetOrderBookResponse.Builder.class);
  }

  public static final int BIDS_FIELD_NUMBER = 1;
  private java.util.List<com.tradeflow.order.OrderBookEntry> bids_;
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflow.order.OrderBookEntry> getBidsList() {
    return bids_;
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
      getBidsOrBuilderList() {
    return bids_;
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  @java.lang.Override
  public int getBidsCount() {
    return bids_.size();
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  @java.lang.Override
  public com.tradeflow.order.OrderBookEntry getBids(int index) {
    return bids_.get(index);
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
   */
  @java.lang.Override
  public com.tradeflow.order.OrderBookEntryOrBuilder getBidsOrBuilder(
      int index) {
    return bids_.get(index);
  }

  public static final int ASKS_FIELD_NUMBER = 2;
  private java.util.List<com.tradeflow.order.OrderBookEntry> asks_;
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflow.order.OrderBookEntry> getAsksList() {
    return asks_;
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
      getAsksOrBuilderList() {
    return asks_;
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  @java.lang.Override
  public int getAsksCount() {
    return asks_.size();
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  @java.lang.Override
  public com.tradeflow.order.OrderBookEntry getAsks(int index) {
    return asks_.get(index);
  }
  /**
   * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
   */
  @java.lang.Override
  public com.tradeflow.order.OrderBookEntryOrBuilder getAsksOrBuilder(
      int index) {
    return asks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bids_.size(); i++) {
      output.writeMessage(1, bids_.get(i));
    }
    for (int i = 0; i < asks_.size(); i++) {
      output.writeMessage(2, asks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bids_.get(i));
    }
    for (int i = 0; i < asks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, asks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflow.order.GetOrderBookResponse)) {
      return super.equals(obj);
    }
    com.tradeflow.order.GetOrderBookResponse other = (com.tradeflow.order.GetOrderBookResponse) obj;

    if (!getBidsList()
        .equals(other.getBidsList())) return false;
    if (!getAsksList()
        .equals(other.getAsksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBidsCount() > 0) {
      hash = (37 * hash) + BIDS_FIELD_NUMBER;
      hash = (53 * hash) + getBidsList().hashCode();
    }
    if (getAsksCount() > 0) {
      hash = (37 * hash) + ASKS_FIELD_NUMBER;
      hash = (53 * hash) + getAsksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflow.order.GetOrderBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflow.order.GetOrderBookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflow.order.GetOrderBookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflow.order.GetOrderBookResponse)
      com.tradeflow.order.GetOrderBookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflow.order.OrderServiceOuterClass.internal_static_tradeflow_order_GetOrderBookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflow.order.OrderServiceOuterClass.internal_static_tradeflow_order_GetOrderBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflow.order.GetOrderBookResponse.class, com.tradeflow.order.GetOrderBookResponse.Builder.class);
    }

    // Construct using com.tradeflow.order.GetOrderBookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBidsFieldBuilder();
        getAsksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        bidsBuilder_.clear();
      }
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        asksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflow.order.OrderServiceOuterClass.internal_static_tradeflow_order_GetOrderBookResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflow.order.GetOrderBookResponse getDefaultInstanceForType() {
      return com.tradeflow.order.GetOrderBookResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflow.order.GetOrderBookResponse build() {
      com.tradeflow.order.GetOrderBookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflow.order.GetOrderBookResponse buildPartial() {
      com.tradeflow.order.GetOrderBookResponse result = new com.tradeflow.order.GetOrderBookResponse(this);
      int from_bitField0_ = bitField0_;
      if (bidsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bids_ = java.util.Collections.unmodifiableList(bids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bids_ = bids_;
      } else {
        result.bids_ = bidsBuilder_.build();
      }
      if (asksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          asks_ = java.util.Collections.unmodifiableList(asks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.asks_ = asks_;
      } else {
        result.asks_ = asksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflow.order.GetOrderBookResponse) {
        return mergeFrom((com.tradeflow.order.GetOrderBookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflow.order.GetOrderBookResponse other) {
      if (other == com.tradeflow.order.GetOrderBookResponse.getDefaultInstance()) return this;
      if (bidsBuilder_ == null) {
        if (!other.bids_.isEmpty()) {
          if (bids_.isEmpty()) {
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBidsIsMutable();
            bids_.addAll(other.bids_);
          }
          onChanged();
        }
      } else {
        if (!other.bids_.isEmpty()) {
          if (bidsBuilder_.isEmpty()) {
            bidsBuilder_.dispose();
            bidsBuilder_ = null;
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bidsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBidsFieldBuilder() : null;
          } else {
            bidsBuilder_.addAllMessages(other.bids_);
          }
        }
      }
      if (asksBuilder_ == null) {
        if (!other.asks_.isEmpty()) {
          if (asks_.isEmpty()) {
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAsksIsMutable();
            asks_.addAll(other.asks_);
          }
          onChanged();
        }
      } else {
        if (!other.asks_.isEmpty()) {
          if (asksBuilder_.isEmpty()) {
            asksBuilder_.dispose();
            asksBuilder_ = null;
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000002);
            asksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAsksFieldBuilder() : null;
          } else {
            asksBuilder_.addAllMessages(other.asks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflow.order.GetOrderBookResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflow.order.GetOrderBookResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tradeflow.order.OrderBookEntry> bids_ =
      java.util.Collections.emptyList();
    private void ensureBidsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bids_ = new java.util.ArrayList<com.tradeflow.order.OrderBookEntry>(bids_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder> bidsBuilder_;

    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public java.util.List<com.tradeflow.order.OrderBookEntry> getBidsList() {
      if (bidsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bids_);
      } else {
        return bidsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public int getBidsCount() {
      if (bidsBuilder_ == null) {
        return bids_.size();
      } else {
        return bidsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public com.tradeflow.order.OrderBookEntry getBids(int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);
      } else {
        return bidsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder setBids(
        int index, com.tradeflow.order.OrderBookEntry value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.set(index, value);
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder setBids(
        int index, com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.set(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder addBids(com.tradeflow.order.OrderBookEntry value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder addBids(
        int index, com.tradeflow.order.OrderBookEntry value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(index, value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder addBids(
        com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder addBids(
        int index, com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder addAllBids(
        java.lang.Iterable<? extends com.tradeflow.order.OrderBookEntry> values) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bids_);
        onChanged();
      } else {
        bidsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder clearBids() {
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bidsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public Builder removeBids(int index) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.remove(index);
        onChanged();
      } else {
        bidsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder getBidsBuilder(
        int index) {
      return getBidsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public com.tradeflow.order.OrderBookEntryOrBuilder getBidsOrBuilder(
        int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);  } else {
        return bidsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
         getBidsOrBuilderList() {
      if (bidsBuilder_ != null) {
        return bidsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bids_);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder addBidsBuilder() {
      return getBidsFieldBuilder().addBuilder(
          com.tradeflow.order.OrderBookEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder addBidsBuilder(
        int index) {
      return getBidsFieldBuilder().addBuilder(
          index, com.tradeflow.order.OrderBookEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry bids = 1;</code>
     */
    public java.util.List<com.tradeflow.order.OrderBookEntry.Builder> 
         getBidsBuilderList() {
      return getBidsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder> 
        getBidsFieldBuilder() {
      if (bidsBuilder_ == null) {
        bidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder>(
                bids_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bids_ = null;
      }
      return bidsBuilder_;
    }

    private java.util.List<com.tradeflow.order.OrderBookEntry> asks_ =
      java.util.Collections.emptyList();
    private void ensureAsksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        asks_ = new java.util.ArrayList<com.tradeflow.order.OrderBookEntry>(asks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder> asksBuilder_;

    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public java.util.List<com.tradeflow.order.OrderBookEntry> getAsksList() {
      if (asksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(asks_);
      } else {
        return asksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public int getAsksCount() {
      if (asksBuilder_ == null) {
        return asks_.size();
      } else {
        return asksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public com.tradeflow.order.OrderBookEntry getAsks(int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);
      } else {
        return asksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder setAsks(
        int index, com.tradeflow.order.OrderBookEntry value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.set(index, value);
        onChanged();
      } else {
        asksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder setAsks(
        int index, com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.set(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder addAsks(com.tradeflow.order.OrderBookEntry value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(value);
        onChanged();
      } else {
        asksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder addAsks(
        int index, com.tradeflow.order.OrderBookEntry value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(index, value);
        onChanged();
      } else {
        asksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder addAsks(
        com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder addAsks(
        int index, com.tradeflow.order.OrderBookEntry.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder addAllAsks(
        java.lang.Iterable<? extends com.tradeflow.order.OrderBookEntry> values) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asks_);
        onChanged();
      } else {
        asksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder clearAsks() {
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        asksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public Builder removeAsks(int index) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.remove(index);
        onChanged();
      } else {
        asksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder getAsksBuilder(
        int index) {
      return getAsksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public com.tradeflow.order.OrderBookEntryOrBuilder getAsksOrBuilder(
        int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);  } else {
        return asksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public java.util.List<? extends com.tradeflow.order.OrderBookEntryOrBuilder> 
         getAsksOrBuilderList() {
      if (asksBuilder_ != null) {
        return asksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(asks_);
      }
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder addAsksBuilder() {
      return getAsksFieldBuilder().addBuilder(
          com.tradeflow.order.OrderBookEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public com.tradeflow.order.OrderBookEntry.Builder addAsksBuilder(
        int index) {
      return getAsksFieldBuilder().addBuilder(
          index, com.tradeflow.order.OrderBookEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflow.order.OrderBookEntry asks = 2;</code>
     */
    public java.util.List<com.tradeflow.order.OrderBookEntry.Builder> 
         getAsksBuilderList() {
      return getAsksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder> 
        getAsksFieldBuilder() {
      if (asksBuilder_ == null) {
        asksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflow.order.OrderBookEntry, com.tradeflow.order.OrderBookEntry.Builder, com.tradeflow.order.OrderBookEntryOrBuilder>(
                asks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        asks_ = null;
      }
      return asksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflow.order.GetOrderBookResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflow.order.GetOrderBookResponse)
  private static final com.tradeflow.order.GetOrderBookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflow.order.GetOrderBookResponse();
  }

  public static com.tradeflow.order.GetOrderBookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOrderBookResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetOrderBookResponse>() {
    @java.lang.Override
    public GetOrderBookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetOrderBookResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetOrderBookResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOrderBookResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflow.order.GetOrderBookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

