// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

package com.tradeflow.order;

public interface ModifyOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflow.order.ModifyOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>double new_price = 2;</code>
   * @return The newPrice.
   */
  double getNewPrice();

  /**
   * <code>int32 new_quantity = 3;</code>
   * @return The newQuantity.
   */
  int getNewQuantity();

  /**
   * <code>string client_id = 4;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 4;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
