// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

package com.tradeflow.order;

public final class OrderServiceOuterClass {
  private OrderServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_SubmitOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_SubmitOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_SubmitOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_SubmitOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_GetOrderBookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_GetOrderBookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_GetOrderBookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_GetOrderBookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_OrderBookEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_OrderBookEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_CancelOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_CancelOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_CancelOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_CancelOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_ModifyOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_ModifyOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_ModifyOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_ModifyOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_SubscribeTradesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_SubscribeTradesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflow_order_TradeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflow_order_TradeUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023order_service.proto\022\017tradeflow.order\"t" +
      "\n\022SubmitOrderRequest\022\016\n\006symbol\030\001 \001(\t\022\014\n\004" +
      "side\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022" +
      "\020\n\010quantity\030\005 \001(\005\022\021\n\tclient_id\030\006 \001(\t\"H\n\023" +
      "SubmitOrderResponse\022\020\n\010order_id\030\001 \001(\t\022\016\n" +
      "\006status\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\"%\n\023GetOrd" +
      "erBookRequest\022\016\n\006symbol\030\001 \001(\t\"t\n\024GetOrde" +
      "rBookResponse\022-\n\004bids\030\001 \003(\0132\037.tradeflow." +
      "order.OrderBookEntry\022-\n\004asks\030\002 \003(\0132\037.tra" +
      "deflow.order.OrderBookEntry\"1\n\016OrderBook" +
      "Entry\022\r\n\005price\030\001 \001(\001\022\020\n\010quantity\030\002 \001(\005\"9" +
      "\n\022CancelOrderRequest\022\020\n\010order_id\030\001 \001(\t\022\021" +
      "\n\tclient_id\030\002 \001(\t\"6\n\023CancelOrderResponse" +
      "\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"b\n\022Mod" +
      "ifyOrderRequest\022\020\n\010order_id\030\001 \001(\t\022\021\n\tnew" +
      "_price\030\002 \001(\001\022\024\n\014new_quantity\030\003 \001(\005\022\021\n\tcl" +
      "ient_id\030\004 \001(\t\"6\n\023ModifyOrderResponse\022\016\n\006" +
      "status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"(\n\026Subscri" +
      "beTradesRequest\022\016\n\006symbol\030\001 \001(\t\"~\n\013Trade" +
      "Update\022\024\n\014buy_order_id\030\001 \001(\t\022\025\n\rsell_ord" +
      "er_id\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\022\020\n\010quantity\030\004" +
      " \001(\005\022\016\n\006symbol\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\t2" +
      "\325\003\n\014OrderService\022X\n\013SubmitOrder\022#.tradef" +
      "low.order.SubmitOrderRequest\032$.tradeflow" +
      ".order.SubmitOrderResponse\022[\n\014GetOrderBo" +
      "ok\022$.tradeflow.order.GetOrderBookRequest" +
      "\032%.tradeflow.order.GetOrderBookResponse\022" +
      "X\n\013CancelOrder\022#.tradeflow.order.CancelO" +
      "rderRequest\032$.tradeflow.order.CancelOrde" +
      "rResponse\022X\n\013ModifyOrder\022#.tradeflow.ord" +
      "er.ModifyOrderRequest\032$.tradeflow.order." +
      "ModifyOrderResponse\022Z\n\017SubscribeTrades\022\'" +
      ".tradeflow.order.SubscribeTradesRequest\032" +
      "\034.tradeflow.order.TradeUpdate0\001B\027\n\023com.t" +
      "radeflow.orderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tradeflow_order_SubmitOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tradeflow_order_SubmitOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_SubmitOrderRequest_descriptor,
        new java.lang.String[] { "Symbol", "Side", "Type", "Price", "Quantity", "ClientId", });
    internal_static_tradeflow_order_SubmitOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tradeflow_order_SubmitOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_SubmitOrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "Status", "Message", });
    internal_static_tradeflow_order_GetOrderBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tradeflow_order_GetOrderBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_GetOrderBookRequest_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_tradeflow_order_GetOrderBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tradeflow_order_GetOrderBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_GetOrderBookResponse_descriptor,
        new java.lang.String[] { "Bids", "Asks", });
    internal_static_tradeflow_order_OrderBookEntry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tradeflow_order_OrderBookEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_OrderBookEntry_descriptor,
        new java.lang.String[] { "Price", "Quantity", });
    internal_static_tradeflow_order_CancelOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tradeflow_order_CancelOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_CancelOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", "ClientId", });
    internal_static_tradeflow_order_CancelOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tradeflow_order_CancelOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_CancelOrderResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_tradeflow_order_ModifyOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tradeflow_order_ModifyOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_ModifyOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", "NewPrice", "NewQuantity", "ClientId", });
    internal_static_tradeflow_order_ModifyOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tradeflow_order_ModifyOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_ModifyOrderResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_tradeflow_order_SubscribeTradesRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tradeflow_order_SubscribeTradesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_SubscribeTradesRequest_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_tradeflow_order_TradeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tradeflow_order_TradeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflow_order_TradeUpdate_descriptor,
        new java.lang.String[] { "BuyOrderId", "SellOrderId", "Price", "Quantity", "Symbol", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
