// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

package com.tradeflow.order;

public interface TradeUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflow.order.TradeUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buy_order_id = 1;</code>
   * @return The buyOrderId.
   */
  java.lang.String getBuyOrderId();
  /**
   * <code>string buy_order_id = 1;</code>
   * @return The bytes for buyOrderId.
   */
  com.google.protobuf.ByteString
      getBuyOrderIdBytes();

  /**
   * <code>string sell_order_id = 2;</code>
   * @return The sellOrderId.
   */
  java.lang.String getSellOrderId();
  /**
   * <code>string sell_order_id = 2;</code>
   * @return The bytes for sellOrderId.
   */
  com.google.protobuf.ByteString
      getSellOrderIdBytes();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string symbol = 5;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 5;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string timestamp = 6;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 6;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
